baseURL = 'https://aadee.xyz/'
languageCode = 'en-us'
title = 'Aadee.xyz'
theme = 'hugo.386'

[params]
    # Main
    mainpagetitle = "Aadee"
    mainpagesubtitle = "I just wanted to put something on my domain"
    mainpagedesc = "Currently stuck between one project and another—welcome to the chaos!"

    # Socials
    twitter = "https://twitter.com/aadeexyz"
    linkedin = "https://linkedin.com/in/aadee"
    github = "https://github.com/aadeexyz"
    overmind = "https://overmind.xyz/@AadeeWasTaken"
    email = "mailto:hello@aadee.xyz"

[params.copyright]
    name = "Aadee"